### PR TITLE
Do not enable semantic version column by default.

### PR DESCRIPTION
**Pull request by christ66**
@reviewbybees

### CODE REVIEW

**Comment by imod** [comment]
+1

**Comment by aheritier** [comment]
why ?

**Comment by christ66** [comment]
@aheritier Setting the "show by default" option changes the default view for every folder created. If I create 20 new folders each will have the deploy now column even if the folder doesn't use it. It just adds more to the default view as well which can not be modified, so you're All view will have this column until a new view is created.

I think it would be better to disable it by default and you select which views and which folders get the view.

**Comment by christ66** [comment]
@ciroque ping?

**Comment by aheritier** [comment]
🐝

**Comment by mfeliciano** [comment]
Could we get this PR moved along, please? I'm hoping it will be a workaround for the problem reported here: https://issues.jenkins-ci.org/browse/JENKINS-40113. (If someone can get to the root cause of that problem, that'd be even better...)

**Comment by christ66** [comment]
@reviewbybees done.

@ciroque I was wondering if this could be merged soon?

**Pull request merged**
